version: "3"
services:
  nginx:
    # image: nginx:1.25-alpine-slim
    build: .
    container_name: nginx
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates/localhost.symitems.click/fullchain1.pem:/etc/nginx/conf.d/localhost.symitems.click.fullchain.pem:Z
      - ./certificates/localhost.symitems.click/privkey1.pem:/etc/nginx/conf.d/localhost.symitems.click.privkey1.pem:Z
      # NGINXのWebアプリ（index.html等）をホストOSから、ゲストOSに連結する
      # - ./html:/usr/share/nginx/html

  ghost:
    image: ghost
    restart: always
    expose:
      - "2368"
